### ISSUE TITLE
Jump only once

### ISSUE THREAD

**Issue by mkawalec** [mkawalec/reason-servant#3]
Right now Mario can basically fly straight up by jumping multiple times. Take this power away from him by only allowing him to jump once.

**Comment by typeofweb** [comment]
MINE

**Comment by Agnishom** [comment]
In some video games, Mario can jump not once but _twice_. See: [Double Jump](http://tvtropes.org/pmwiki/pmwiki.php/Main/DoubleJump)

**Comment by mkawalec** [comment]
write the code, any feature is a good feature :P
